<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-02T17:15:05 IST" name="Suite" finished-at="2024-12-02T17:15:18 IST" duration-ms="13482">
    <groups>
      <group name="Regression">
        <method signature="TC2_Blogger.Validate_footer_ThemImage_clickable()[pri:0, instance:TestCases.TC2_Blogger@b9b00e0]" name="Validate_footer_ThemImage_clickable" class="TestCases.TC2_Blogger"/>
      </group> <!-- Regression -->
      <group name="master">
        <method signature="TC2_Blogger.Validate_footer_ThemImage_clickable()[pri:0, instance:TestCases.TC2_Blogger@b9b00e0]" name="Validate_footer_ThemImage_clickable" class="TestCases.TC2_Blogger"/>
      </group> <!-- master -->
    </groups>
    <test started-at="2024-12-02T17:15:05 IST" name="Test" finished-at="2024-12-02T17:15:18 IST" duration-ms="13482">
      <class name="TestCases.TC2_Blogger">
        <test-method is-config="true" signature="SetUpUrl(java.lang.String)[pri:0, instance:TestCases.TC2_Blogger@b9b00e0]" started-at="2024-12-02T17:15:05 IST" name="SetUpUrl" finished-at="2024-12-02T17:15:14 IST" duration-ms="8821" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpUrl -->
        <test-method signature="Validate_footer_ThemImage_clickable()[pri:0, instance:TestCases.TC2_Blogger@b9b00e0]" started-at="2024-12-02T17:15:14 IST" name="Validate_footer_ThemImage_clickable" finished-at="2024-12-02T17:15:18 IST" duration-ms="3770" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at TestCases.TC2_Blogger.Validate_footer_ThemImage_clickable(TC2_Blogger.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validate_footer_ThemImage_clickable -->
        <test-method is-config="true" signature="mainTearDown()[pri:0, instance:TestCases.TC2_Blogger@b9b00e0]" started-at="2024-12-02T17:15:18 IST" name="mainTearDown" finished-at="2024-12-02T17:15:18 IST" duration-ms="227" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mainTearDown -->
      </class> <!-- TestCases.TC2_Blogger -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
